knp_paginator:
    page_range: 5                       # Nombre de pages visibles dans la pagination
    default_options:
        page_name: page                 # Paramètre de requête pour la pagination
        sort_field_name: sort           # Paramètre de requête pour trier les colonnes
        sort_direction_name: direction  # Paramètre pour l'ordre de tri
        distinct: true                  # Pour éviter les doublons
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'
